
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Gabarito, Swanky_and_Moo_Moo } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const hFont = Gabarito({
  variable: "--h-font",
  weight: "400",
  subsets: ["latin"],
});

const pFont = Gabarito({
  variable: "--p-font",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hFont.variable} ${pFont.variable}`} suppressHydrationWarning>
        {/* <Header /> */}
        <main>
            {children}
        </main>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
