
import type { Metadata } from "next";
import { Walter_Turncoat, Swanky_and_Moo_Moo } from "next/font/google";
import "./globals.css";
import Template from "./template";

const hFont = Walter_Turncoat({
  variable: "--h-font",
  weight: "400",
  subsets: ["latin"],
});

const pFont = Swanky_and_Moo_Moo({
  variable: "--p-font",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hFont.variable} ${pFont.variable}`} suppressHydrationWarning>
        <Template>
            {children}
        </Template>
      </body>
    </html>
  );
}
